// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRqRhoFl9HX5XSa-m9HN10OsZ4flt1HWI',
    appId: '1:753791777525:web:98a833435165dcdce7e3bc',
    messagingSenderId: '753791777525',
    projectId: 'job-portal-47060',
    authDomain: 'job-portal-47060.firebaseapp.com',
    storageBucket: 'job-portal-47060.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApVfoXvafx4akTR9iLhX0b2anBVNgorGA',
    appId: '1:753791777525:ios:6446b18456f087b5e7e3bc',
    messagingSenderId: '753791777525',
    projectId: 'job-portal-47060',
    storageBucket: 'job-portal-47060.appspot.com',
    iosBundleId: 'com.example.jobPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRqRhoFl9HX5XSa-m9HN10OsZ4flt1HWI',
    appId: '1:753791777525:web:5d6ce5e71f0f07e3e7e3bc',
    messagingSenderId: '753791777525',
    projectId: 'job-portal-47060',
    authDomain: 'job-portal-47060.firebaseapp.com',
    storageBucket: 'job-portal-47060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApVfoXvafx4akTR9iLhX0b2anBVNgorGA',
    appId: '1:753791777525:ios:6446b18456f087b5e7e3bc',
    messagingSenderId: '753791777525',
    projectId: 'job-portal-47060',
    storageBucket: 'job-portal-47060.appspot.com',
    androidClientId: '753791777525-qntoe4s3pt5gpjbu0ih668bh15vu550b.apps.googleusercontent.com',
    iosClientId: '753791777525-oa9hgmae1c1madouoko3s3suu1ahd9p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobPortal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpVyye47KiQavIFkVuzBKTq4O_B7ctWs',
    appId: '1:753791777525:android:24a2886dd5305b25e7e3bc',
    messagingSenderId: '753791777525',
    projectId: 'job-portal-47060',
    storageBucket: 'job-portal-47060.appspot.com',
  );

}